shell/flk: sudo nixos-generate-config
```
$ btrfs subvol show / >/dev/null; printf "%s\n" "$?"
ERROR: Could not search B-tree: Operation not permitted
1
```

Btrfs's `ioctl()` `BTRFS_IOC_TREE_SEARCH` requires elevation.
`btrfs subvol show <path>` may be called by `nixos-generate-config`, and
if `btrfs subvol show <path>` fails then `nixos-generate-config` fails.

Fixes `flk up` failures due to the presence of Btrfs volumes.